FROM rust:1.80-slim-bookworm
WORKDIR /
RUN apt -y update
RUN apt install -y curl tar wget aria2 clang pkg-config libssl-dev jq build-essential git make ncdu cmake ninja-build

# Install SP1
RUN git clone https://github.com/succinctlabs/sp1.git
RUN cd sp1 && \
    git checkout v1.0.1 && \
    cd cli && \
    cargo install --locked --path . && \
    cd / && \
    cargo prove install-toolchain

COPY ./private_repos/blob-stream-inclusion.tar.gz /

RUN tar xf /blob-stream-inclusion.tar.gz && \
    rm /blob-stream-inclusion.tar.gz

RUN cd /blob-stream-inclusion && \
    cd blobstream/script

WORKDIR /blob-stream-inclusion/blobstream/script
CMD ["cargo", "run", "--release"]

#CMD ["sleep", "infinity"]
## Set up a dummy SSH key

#RUN mkdir /root/.ssh
#RUN ssh-keygen -t ed25519 -f /root/id_ed25519.key -N "" -C "autogenerated-key" && \
    #chmod 600 /root/id_ed25519.key && \
    #eval "$(ssh-agent -s)" && \
    #ssh-add /root/id_ed25519.key
    ##cargo prove build-toolchain

##CMD ["git", "--version"]
#CMD ["bash"]
